bot:
  token: ""
  activity: "👀 Checking users"
  rolesId:
    - "264156076079972374" # AyTeam
    - "264488569450528768" # Modérateurs

aystone:
  url: ""
  token: ""

twitch:
  apiUrl: "https://api.twitch.tv/helix"
  tokenUrl: "https://id.twitch.tv/oauth2/token"
  clientId: ""
  clientSecret: ""

database:
  host: ""
  port: ""
  name: ""
  schema: ""
  username: ""
  password: ""